version: '3.8'

services:
  gui-container:
    build: .
    container_name: ubuntu-gui
    privileged: true
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - gui-data:/opt/gui-container
    restart: unless-stopped
    environment:
      - DISPLAY=:1
      - VNC_RESOLUTION=${VNC_RESOLUTION:-1280x720}

volumes:
  gui-data:
